[project]
name = "hiregraph"
version = "0.1.0"
requires-python = ">=3.11"

dependencies = [
    "langgraph",
    "langchain",
    "langchain-openai",
    "langchain-community",
    "langchain-core",
    "pydantic",
    "python-dotenv",
    "fastapi",
    "uvicorn",
    "streamlit",
    "pytest",
    "tavily-python"
]